### ISSUE TITLE
Does not work with Angular 2.1.18

### ISSUE THREAD

**Issue by KeksKlip** [angular-ui/ui-select#96]
```
TypeError: undefined is not a function
    at htmlParser (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular-sanitize.js:249:17)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular-sanitize.js:143:7
    at getTrusted (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:119:16)
    at Object.e.(anonymous function) [as getTrustedHtml] (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:120:267)
    at Object.fn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:191:205)
    at k.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:109:375)
    at k.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:112:362)
    at h (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:72:327)
    at x (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:77:288)
    at XMLHttpRequest.z.onreadystatechange (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular.min.js:78:340) 
```
