### PR TITLE
fix: make compatible with Angular 1.5 and non-cached templates

### LINKED ISSUE #1239: Does not work with latest angular 1.5.0-build...
```
Error: [ui.select:transcluded] http://errors.angularjs.org/1.5.0-build.4310+sha.0c8a9a0/ui.select/transcluded?p0=Expected%201%20.ui-select-match%20but%20got%20'%7B0%7D'.&p1=0
    at ...ommitted...
    at http://localhost:8000/scripts/support/uiselect.js:968:19
    at ...ommitted...
    at ...ommitted...
    at ...ommitted...
    at p (...ommitted...)
    at uis.directive.$timeout.compile (http://localhost:8000/scripts/support/uiselect.js:956:9)
    at ca (...ommitted...)
    at L (...ommitted...)
    at ...ommitted... <div class="ui-select-container ui-select-bootstrap dropdown" ng-class="{open: $select.open}" ng-model="foundItem.selected" theme="bootstrap" reset-search-input="false" on-select="selectedSearch($item, $model)" style="width: 80%">(anonymous function) @ ...ommitted...(anonymous function) @ ...ommitted...:86(anonymous function) @ ...ommitted...:10616ca @ ...ommitted...:79L @ ...ommitted...:67(anonymous function) @ ...ommitted...:74(anonymous function) @ ...ommitted...:124n.$eval @ ...ommitted...:139n.$digest @ ...ommitted...:136n.$apply @ ...ommitted...:139(anonymous function) @ ...ommitted...:4490n.event.dispatch @ ...ommitted...:3r.handle @ ...ommitted...:3
```

### LINKED ISSUE #1325: ui-select broken with angular 1.5.0 beta2
Ui-select doesn't work with latest angularjs updates

### LINKED ISSUE #1356: Breaks with angular 1.5-rc.0
image

### LINKED ISSUE #1422: When i upgrade angular version 1.5.0-rc.2  then it is not working
angular.js:13307 Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'.
    at http://test.com:9012/library/ui-select/dist/select.js:125:12
    at http://test.com:9012/library/ui-select/dist/select.js:1035:19
    at publicLinkFn (http://test.com:9012/bower_components/angular/angular.js:8193:29)
    at http://test.com:9012/bower_components/angular/angular.js:8535:29
    at boundTranscludeFn (http://test.com:9012/bower_components/angular/angular.js:8332:16)
    at controllersBoundTransclude (http://test.com:9012/bower_components/angular/angular.js:9108:20)
    at http://test.com:9012/library/ui-select/dist/select.js:1023:9
    at invokeLinkFn (http://test.com:9012/bower_components/angular/angular.js:9580:9)
    at nodeLinkFn (http://test.com:9012/bower_components/angular/angular.js:9066:11)

### PR DESCRIPTION
**Pull request by Narretz**
In Angular 1.5, transcluded content is linked lazily.
For uiSelect that means the clone in the transclude function is not compiled and linked yet, so
uiSelect cannot detect the match and choices elements by their classnames, because they haven't been
set yet (which happens by replacing the elements with the templates).
However, the templateUrl function is executed at this point, so we can use it to add the
class names to the directive elements.

On another note, this behavior also affected versions earlier than 1.5.0-beta.2, when the template
of ui-select-match or ui-select-choices wasn't cached. In that case, the async compilation of
the template would mean also that the clone in the transclude function wasn't compiled yet, and so
the classes wouldn't be set either.

Closes #1422
Closes #1356
Closes #1325
Closes #1239

### CODE REVIEW

**Comment by Narretz** [comment]
@aaronroberson This fixes ui-select with angular 1.5. Can you please review / merge this? It seems to affect lots of people.

**Comment by aaronroberson** [comment]
@Narretz Thanks!

**Comment by adarshbhat** [comment]
Thank you, @Narretz ! :smile:
